name: callwave_flutter_workspace
publish_to: none

environment:
  sdk: "^3.11.0"

dev_dependencies:
  melos: ^7.4.0

workspace:
  - packages/callwave_flutter
  - packages/callwave_flutter_method_channel
  - packages/callwave_flutter_platform_interface
  - packages/callwave_flutter/example

melos:
  scripts:
    analyze:
      run: dart run melos exec -- flutter analyze
    test:
      run: dart run melos exec -- flutter test
