name: callwave_flutter
description: Flutter plugin for WhatsApp-style VoIP call UX.
version: 0.1.0
homepage: https://github.com/callwave/callwave_flutter
license: MIT

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  callwave_flutter_platform_interface: ^0.1.0
  callwave_flutter_method_channel: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: callwave_flutter_method_channel
      ios:
        default_package: callwave_flutter_method_channel

dependency_overrides:
  callwave_flutter_platform_interface:
    path: ../callwave_flutter_platform_interface
  callwave_flutter_method_channel:
    path: ../callwave_flutter_method_channel
